### ISSUE TITLE
BUILD FAILURE maven repo missing in POM

### ISSUE THREAD

**Issue by BillYJT** [nextworks-it/timeo#1]
**Describe Bug**
Hi, I encountered the following error when trying to install TIMEO following the README instruction. This is the full log when running `mvn clean package`

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for it.nextworks.nfvmano:Timeo:jar:0.0.2-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for dk.ange.octave:javaoctave:jar should not point at files within the project directory, ${project.basedir}/lib/javaoctave/javaoctave-0.6.1.jar will be unresolvable by dependent projects @ line 239, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< it.nextworks.nfvmano:Timeo >---------------------
[INFO] Building TIMEO 0.0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.swagger:swagger-java-client-monit-config-manager:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.770 s
[INFO] Finished at: 2020-07-29T08:58:51+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Timeo: Could not resolve dependencies for project it.nextworks.nfvmano:Timeo:jar:0.0.2-SNAPSHOT: Failure to find io.swagger:swagger-java-client-monit-config-manager:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**To reproduce**
`~/Projects/timeo$ ./dep_setup.sh `
`~/Projects/timeo$ ./install_libs.sh ~/Projects/`
`~/Projects/timeo$ cd TIMEO`
`~/Projects/timeo/TIMEO$ mvn clean package`

It appears to me that this may be caused by 'The POM for io.swagger:swagger-java-client-monit-config-manager:jar:1.0.0 is missing'.
I only come across maven when I found out about this project, so I am very new to this subject. Could you advice how I may resolve this? Thank you.

**Comment by jbrenes** [comment]
Hi,

We have just pushed a fix for this. The problem was that even though the ConfigManagerApi project was included in the repo and configured as a dependency in TIMEO, it was not being built by the install_libs script. Let us know if you have any further issues.

BR

Juan Brenes

**Comment by BillYJT** [comment]
@jbrenes Thank you for your reply. However, running `./install_libs.sh <folder>` now gives the following error.

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ swagger-java-client-monit-config-manager ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 31 source files to /home/bill/Projects/timeo/ConfigManagerApi/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/ApiException.java:[18,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Alert.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/KVP.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Pair.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Exporter.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Endpoint.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Dashboard.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardPanel.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Configuration.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/StringUtil.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/ApiKeyAuth.java:[20,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/OAuth.java:[20,18] package javax.annotation does not exist
[INFO] 18 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.213 s
[INFO] Finished at: 2020-07-29T20:03:44+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-java-client-monit-config-manager: Compilation failure: Compilation failure: 
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/ApiException.java:[18,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Alert.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/KVP.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Pair.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Exporter.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Endpoint.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardQueryResult.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Dashboard.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardPanel.java:[28,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Configuration.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterDescription.java:[31,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/StringUtil.java:[15,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/ApiKeyAuth.java:[20,18] package javax.annotation does not exist
[ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/OAuth.java:[20,18] package javax.annotation does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

The original error persists when running `mvn clean package` in `<repo-root>/TIMEO/`

**Comment by BillYJT** [comment]
> @jbrenes Thank you for your reply. However, running `./install_libs.sh <folder>` now gives the following error.
> 
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ swagger-java-client-monit-config-manager ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 31 source files to /home/bill/Projects/timeo/ConfigManagerApi/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/ApiException.java:[18,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Alert.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/KVP.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Pair.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Exporter.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Endpoint.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Dashboard.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardPanel.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Configuration.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/StringUtil.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/ApiKeyAuth.java:[20,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/OAuth.java:[20,18] package javax.annotation does not exist
> [INFO] 18 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.213 s
> [INFO] Finished at: 2020-07-29T20:03:44+10:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-java-client-monit-config-manager: Compilation failure: Compilation failure:
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/ApiException.java:[18,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Alert.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/AlertDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/KVP.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Pair.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Exporter.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Endpoint.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardQueryResult.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/Dashboard.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/DashboardPanel.java:[28,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/Configuration.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/model/ExporterDescription.java:[31,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/StringUtil.java:[15,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/ApiKeyAuth.java:[20,18] package javax.annotation does not exist
> [ERROR] /home/bill/Projects/timeo/ConfigManagerApi/src/main/java/io/swagger/client/auth/OAuth.java:[20,18] package javax.annotation does not exist
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 
> The original error persists when running `mvn clean package` in `<repo-root>/TIMEO/`

Adding the following lines to pom.xml seems to fix it. Could you verify?

```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```
However, this only lets me stumble into the next problem.. I now have the following errors.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project swagger-java-client-monit-config-manager: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/bill/Projects/timeo/ConfigManagerApi/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I suspect this is due to my java version/ setup, could you advise on this? If it is more appropriate to discuss this under a new issue, please let me know.

Thank you for your help.
Bill

**Comment by BillYJT** [comment]
I can build ConfigManagerApi successfully after changing `maven-javadoc-plugin` version to 3.1.0, `./install_libs` now runs successfully.
Now getting test errors when running `mvn clean package` in TIMEO\

```
Results :

Tests in error: 
  TimeoApplicationTests.contextLoads » IllegalState Failed to load ApplicationCo...

Tests run: 50, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:03 min
[INFO] Finished at: 2020-07-30T10:12:04+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project Timeo: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/bill/Projects/timeo/TIMEO/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]

```

**Comment by jbrenes** [comment]
Hi Bill,

Please, use JDK 8 as the reference version. Installation files have been updated to check the system for that version. 
If you really need to use JDK 11, the versions you propose for the dependencies seem to work. However, the system has been tested only with JDK 8 and the original dependencies version.

BR
Juan

**Comment by BillYJT** [comment]
Thank you! Installed successfully with JDK 8.
May I also ask if there is a GUI session that is supposed to go with the suite, and if yes, how I could launch it? Thanks a lot!

**Comment by jbrenes** [comment]
Hi Bill,

Yes, there is a WEB based GUI under the TIMEO_WEB_GUI folder. I have just pushed  a README that explains the installation instructions. Since the issue with the Java version has been solved I will close the issue, do not hesitate to open a new one if you have any other issues.

BR

Juan
